server:
  port: 10100
  cache:
    cache-names: sjes-elasticsearch
eureka:
  instance:
    hostname: srv3.sanjiang.info
  client:
    serviceUrl:
      defaultZone: http://srv3.sanjiang.info:8761/eureka/
spring:
  data:
    elasticsearch:
      cluster-nodes: srv4.sanjiang.info:9300
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
elasticsearch-backup:
  url: http://srv4.sanjiang.info:9200         #elasticsearch地址
  indices: sjes                               #备份的索引
  repository:
    name: es_backup                           #本地备份仓库的名称
    location: /home/zhangbaiqiang/es_backup   #本地备份仓库的位置
  snapshot: snapshot_index                    #快照名称
  retry:
    backup: 1                                 #备份失败重试次数
    restore: 1                                #恢复失败重试次数