server:
  port: 10100
  cache:
    cache-names: sjes-elasticsearch
eureka:
#  instance:
#    hostname: srv3.sanjiang.info
  client:
    serviceUrl:
      defaultZone: http://srv3.sanjiang.info:8761/eureka/
spring:
  data:
    elasticsearch:
      cluster-nodes: srv4.sanjiang.info:9300
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000